#!/bin/bash

set -e

# alp で解析
echo
echo ":: ACCESS LOG       ====>"
# TODO: フィルターを良い感じに調整する
sudo cat /var/log/nginx/access.log | alp ltsv -m '' --sort=sum -r -o count,uri,min,max,sum,avg | slackcat -c activity-isucon12 --filetype txt
