#!/bin/bash

set -e

# nginx のログを削除
echo ":: CLEAR LOGS       ====>"
sudo truncate -s 0 -c /var/log/nginx/access.log

# 各種サービスの再起動
echo
echo ":: RESTART SERVICES ====>"
# TODO: 大会用のアプリケーション・ミドルウェアに合わせて書き換える
# sudo systemctl restart mysql
# sudo systemctl restart isucon.go
# sudo systemctl restart nginx
